import { Navbar } from "@/components/Navbar/Navbar";
import { SmoothScrollProvider } from "@/components/SmoothScrollProvider/SmoothScrollProvider";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Antonio } from "next/font/google";
import { Humane } from "./_fonts";
import "./_styles/globals.css";

const antonio = Antonio({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-antonio",
});

export const metadata: Metadata = {
  title: "Mohamed Sanjeed - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          Humane.variable,
          antonio.className,
          antonio.variable,
          "antialiased"
        )}
      >
        <Navbar />
        <SmoothScrollProvider>{children}</SmoothScrollProvider>
        <Toaster />
      </body>
    </html>
  );
}
